config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: mydb
      host: localhost
      pass: password
      port: 3000
      schema: trans
      threads: 8
      type: postgres
      user: postgres
  target: prod
